name = "simpleproxy-function-ui"
main = "src/control_entry.js"
compatibility_date = "2026-03-01"
workers_dev = true

[[kv_namespaces]]
binding = "CONFIG"

[[rules]]
type = "Text"
globs = ["**/ui/templates/*.js"]
fallthrough = true
